language: php

php:
    - 5.4
    - 5.5

matrix:
    fast_finish: true

env:
  - MAKE=drupal.make
  - MAKE=project-api.make
  - MAKE=project-headless.make

before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer global require drush/drush:~7.0.0-alpha1
    - drush make --concurrency=4 $MAKE $(pwd)/www/

script: phpunit tests/*

notifications:
  email: false
