language: php
php: [5.6, 7.0]
matrix:
    fast_finish: true
env:
  - MAKE=drupal.make
  - MAKE=project-test.make
  - MAKE=project-api.make
  - MAKE=project-headless.make
  - MAKE=project-blog.make
install:
    - composer selfupdate
    - export CLONE=$(pwd)
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - cd ${CLONE}/scripts
    - composer install
    - composer global require drush/drush:~7.0.0-alpha1
    - drush make --no-recursion --concurrency=4 ${CLONE}/${MAKE} ${CLONE}/www/
cache:
  directories:
  - ~/.drush/cache
  - ~/.composer/cache
before_script:
    - cd ${CLONE}
script: phpunit -v
notifications: { email: false }
